### ISSUE TITLE
Failed to connect to OpenAI realtime

### ISSUE THREAD

**Issue by hello2tomoki** [monuminu/AOAI_Samples#5]
Failed to connect to OpenAI realtime.

App start with  "Hi, Welcome to ShopMe. How can I help you?. Press P to talk!"
When I try to activate the talk, it will try to connect to API.

Failed to connect to OpenAI realtime: https://xxx.openai.azure.com//openai/realtime?xxx isn't a valid URI: scheme isn't ws or wss

its trying to make connection using https instead of wss

Anyone getting this issues?

**Comment by mukundhareddy1996** [comment]
I even tried running the code locally. I was stopped with the same error. 

![image](https://github.com/user-attachments/assets/731777ad-4685-49b0-a830-334f416bceef)

Details:
Model region - East US 2 from azure OpenAI

**Comment by mukundhareddy1996** [comment]
@hello2tomoki replace the .env file AZURE_OPENAI_ENDPOINT
from "https" to "wss" as below

AZURE_OPENAI_ENDPOINT=wss://name.openai.azure.com

**Comment by hello2tomoki** [comment]
Yes, it worked. Thanks
